version: '3'
services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-vue-docker-bookstore
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel-vue-docker-bookstore
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080

  db:
    image: mysql:8.0.17
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: laravel-vue-docker-bookstore-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: laravel-vue-docker-bookstore-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8008:80"

    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

